更新 bloom （托盘）图标 和  Vintage 光标主题
linuxdeepin/deepin-icon-theme pull request #60
Opened 2023-03-28 06:48 UTC by kegechen

2023-03-28 07:01 UTC, BLumia approved these changes

2023-03-28 07:05 UTC, caixr23 submitted a review, later dismissed

2023-03-28 07:19 UTC, BLumia requested changes
![image](https://user-images.githubusercontent.com/10095765/228158771-d88a2735-4c2c-4cba-a592-32ae1f4f6b76.png)

重新确认下这些文件

2023-03-28 09:47 UTC, kegechen commented
确实文件的软链接失效，再处理一下打包问题。

2023-03-29 02:24 UTC, BLumia approved these changes
这回看着对了

2023-03-29 02:26 UTC, BLumia commented
5k+ change，review 界面都卡哭了 :joy:

建议同时本地验证下，确实没问题再合并。

2023-03-29 02:47 UTC, kegechen commented
> 5k+ change，review 界面都卡哭了 joy
> 
> 建议同时本地验证下，确实没问题再合并。

sudo dpkg -i ../deepin-icon-theme_2021.06.09-1_all.deb 
dpkg: 警告: 无法删除原有的目录 /usr/share/icons/Vintage ：目录非空

除了这个小问题，都还好，更新后没有删除旧的文件，删除失败，导致出现大写小写的目录都在。可能是dpkg的问题？

![image](https://user-images.githubusercontent.com/23466548/228413480-6ddc6078-ac17-4541-aaf7-e1f2a3d16997.png)

2023-03-29 03:25 UTC, kegechen commented
/merge

2023-03-29 03:26 UTC, merged